[tool.poetry]
name = "hybridagi"
version = "0.2.001"
description = "The Programmable Neuro-Symbolic AGI"
authors = ["YoanSallami - SynaLinks"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
python-dotenv = ">=1.0.1"
sentence-transformers = ">=2.6.0"
duckduckgo-search = ">=5.2.1"
falkordb = ">=1.0.3"
dspy-ai = ">=2.4.9"
colorama = ">=0.4.6"
mistralai = ">=0.1.8"
faiss-cpu = ">=1.8.0"
tree-sitter = ">=0.22"
tree-sitter-python = ">=0.21"
codeshield = ">=1.0.1"
jupyter-client = ">=8.3.0"
jupyter-core = ">=5.5.0"
ipykernel = ">=6.29.4"
pillow = ">=10.3.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
